import Head from "next/head";
import { getAllPosts } from "@/utils/post";
import Card from "../components/card";
import { Inter } from "next/font/google";
import Layout from "./../components/layout/index";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ postData }) {
  console.log(postData);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Layout>
            {postData?.map((post, index) => (
              <Card key={index} post={post} />
            ))}
          </Layout>
        </div>
      </main>
    </>
  );
}
export const getStaticProps = () => {
  const postData = getAllPosts();

  return {
    props: {
      postData,
    },
  };
};
